test_suites:
    - name: PushNugetToArtifactory
      script_name: nuget_push
      script_path: /root/okta/okta-oidc-xamarin
      sort_order: '1'
      timeout: '15'
      criteria: MERGE
      queue_name: small
      
