test_suites:
    - name: Run Unit Tests
      script_name: unit_tests
      script_path: /root/okta/okta-oidc-xamarin/.okta
      sort_order: '1'
      timeout: '15'
      criteria: MERGE
      queue_name: small
        
task_triggers:
  post_merge:
    - XamarinNugetArtifactoryUpload
      
