version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.1
  general-platform-helpers: okta/general-platform-helpers@1.9

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

jobs:
  build:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Check dotnet version
          command: dotnet --version
      - run:
          name: Clone https version (since git ssh may not be available)
          command: |
            rm -rf .git
            git init
            git remote add origin https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
            git fetch origin
            git checkout -b ${CIRCLE_BRANCH} origin/${CIRCLE_BRANCH}
      - run:
          name: Restore dependencies
          command: |
            dotnet restore ./Okta.Xamarin/Okta.Xamarin/Okta.Xamarin.csproj
            dotnet restore ./Okta.Xamarin/Okta.Xamarin.iOS/Okta.Xamarin.iOS.csproj  
            dotnet restore ./Okta.Xamarin/Okta.Xamarin.Android/Okta.Xamarin.Android.csproj
            dotnet restore ./Okta.Xamarin/Tests/Okta.Xamarin.Test/Okta.Xamarin.Test.csproj
      - run:
          name: Build solution
          command: dotnet build ./Okta.Xamarin/Okta.Xamarin.sln
      - persist_to_workspace:
          root: .
          paths:
            - "*"

  reversing-labs:
    executor: dotnet-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Python and dependencies
          command: |
            apt-get update
            apt-get install -y curl python3 python3-pip unzip
            pip3 install --upgrade pip
      - run:
          name: Download Reverse Labs Scanner
          command: |
            curl https://dso-resources.oktasecurity.com/scanner \
              -H "x-api-key: $DSO_RLSECURE_TOKEN" \
              --output rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      - run:
          name: Install RL Wrapper
          command: |
            pip3 install ./rl_wrapper-0.0.2+35ababa-py3-none-any.whl
      - aws-cli/setup:
          profile_name: default
          role_arn: $AWS_ARN
          region: us-east-1
      - run: >-
          eval "$(aws configure export-credentials --profile default --format env)" 2> /dev/null
      - run:
          name: Run Reversing Labs Wrapper Scanner
          command: |
            rl-wrapper \
              --artifact ${CIRCLE_WORKING_DIRECTORY/#\~/$HOME} \
              --name $CIRCLE_PROJECT_REPONAME\
              --version $CIRCLE_SHA1\
              --repository $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --commit $CIRCLE_SHA1 \
              --build-env "circleci" \
              --suppress_output

  snyk-scan:
    executor: dotnet-executor
    steps:
      - attach_workspace:
          at: .
      - general-platform-helpers/step-setup-artifactory-bazel:
          jfrog_token: ARTIFACTORY_TOKEN
      - general-platform-helpers/step-snyk-dotnet-scan:
          artifact_dir: Okta.Xamarin/Okta.Xamarin

workflows:
  build-and-snyk:
    jobs:
      - build
      - snyk-scan:
          requires:
            - build
          context:
            - static-analysis
          filters:
            branches:
              only:
                - master
                - /^OKTA-.*/

  "Malware Scanner":
    jobs:
      - build
      - reversing-labs:
          requires:
            - build
          context:
            - static-analysis
